name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Oi! Muito obrigado por essa issue nova : )  É a sua primeira né?"
        pr-message: "Oi! Muito obrigado por esse pull request novo : )  É a sua primeira né?"
